[project]
name = "GraphPangenomePipeline"
version = "1.0.0"
description = "The graph pangenome assembly and analysis pipeline"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.0",
    "rich>=14.3.2",
    "typer>=0.21.1",
]
