# basic path config
[Global]
work_dir = "./work"
filePrefix = "ocu"


# ---Cactus Config---
# cactus path config
[Cactus]
seqFile = "./seqfile"
reference = "sy"
maxCores = 24
# if use singularity
singularityImage = "/ME4012_Vol0002/user_home/XiangY/sif/cactus_lastest.sif"
# cactus output control, this arg default --* full
[CactusOutFormat]
vcf = true
gfa = true
gbz = true

# ---vg config---
[VgStats]
# enable vg stats
stats = true
# enable vg paths
paths = true

[VgIndex]
autoindex = true
threads=8

# ---annotate config---
[Annotation]
gff3 = "/ME4012_Vol0002/user_home/XiangY/genome/sy_rmTE_chr.gff3"
SourceGenome = "sy"
singularityImage = "/ME4012_Vol0002/user_home/XiangY/sif/Grannot.sif"
## ---Grannot config---
[Gaf]
Gaf = true

# 可以接收自定义参数 (全称输入)
[ann]
annotation = true
pav_matrix = true
target = ""

# ---vg wgs map config---
[wgs]
DataTable = "/ME4012_Vol0002/user_home/XiangY/work/map_pangenome/test_pipeline/datatable.csv"
Parallel_job = 1
Threads = 8
MinMapQ = 0

# ---vg call variant config---
[call]
Threads = 8
Parallel_job = 1

# ---rna-seq config---
[rna]
gff3 = ""
DataTable = ""
Threads = 8
Parallel_job = 1