# basic path config
[Global]
work_dir = "./work"
filePrefix = "ocu_pangenome"


# ---Cactus Config---
# cactus path config
[Cactus]
seqFile = "./seqfile"
reference = "sy"
maxCores = 24

# cactus output control
[CactusOutFormat]
vcf = true
gfa = true
gbz = true

# ---vg config---
[VgStats]
# enable vg stats
stats = true
# enable vg paths
paths = true

[VgIndex]
autoindex = true
threads=8