# basic path config
[Paths]
work_dir = "./work"

# ---Cactus Config---
# cactus path config
[Cactus]
seqFile = "./seqfile"
reference = ""
outName = ""
maxCores = 24

# cactus output control
[CactusOutFormat]
vcf = true
gfa = true
gbz = true