# basic path config
[Global]
work_dir = "./work"
filePrefix = ""


# ---Cactus Config---
# cactus path config
[Cactus]
seqFile = "./seqfile"
reference = ""
maxCores = 24

# cactus output control
[CactusOutFormat]
vcf = true
gfa = true
gbz = true